// <auto-generated />
using System;
using Medport.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medport.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312012825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medport.Domain.Entities.AgencyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimatedArrival")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResponseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResponseTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("TripId");

                    b.ToTable("AgencyResponse");
                });

            modelBuilder.Entity("Medport.Domain.Entities.BackhaulOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Efficiency")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RevenueBonus")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TripId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripId2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BackhaulOpportunity");
                });

            modelBuilder.Entity("Medport.Domain.Entities.CategoryDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.HasIndex("OptionId")
                        .IsUnique();

                    b.ToTable("CategoryDefault");
                });

            modelBuilder.Entity("Medport.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FixedCosts")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OverheadRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VariableCosts")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CostCenter");
                });

            modelBuilder.Entity("Medport.Domain.Entities.DropdownCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("DropdownCategory");
                });

            modelBuilder.Entity("Medport.Domain.Entities.DropdownOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("DropdownOption");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityType");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("Medport.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLog");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptsNotifications")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvailabilityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("int");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotificationMethods")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricingStructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceArea")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceRadius")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationType");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("Medport.Domain.Entities.OrganizationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TargetOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TargetOrganizationId");

                    b.HasIndex("OrganizationId", "PreferenceType", "TargetOrganizationId")
                        .IsUnique()
                        .HasFilter("[TargetOrganizationId] IS NOT NULL");

                    b.ToTable("OrganizationPreference");
                });

            modelBuilder.Entity("Medport.Domain.Entities.PickupLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("IsActive");

                    b.ToTable("PickupLocation");
                });

            modelBuilder.Entity("Medport.Domain.Entities.PricingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BariatricPricing")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("BaseRates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistanceTiers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceRates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IsolationPricing")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MonitoringPricing")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OxygenPricing")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("PeakHourMultipliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerMileRates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityMultipliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeasonalMultipliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeekendMultipliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneMultipliers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PricingModel");
                });

            modelBuilder.Entity("Medport.Domain.Entities.RouteOptimizationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BackhaulBonusWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BackhaulDistanceLimit")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("BackhaulRevenueBonus")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("BackhaulTimeWindow")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CrewAvailabilityWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeadheadMileWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EnableBackhaulOptimization")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableRealTimeOptimization")
                        .HasColumnType("bit");

                    b.Property<decimal>("EquipmentCompatibilityWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDeadheadMiles")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MaxOptimizationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxOvertimeHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("MaxResponseTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxServiceDistance")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MaxWaitTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("OptimizationAlgorithm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OvertimeRiskWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PatientPriorityWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RevenueWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TargetEfficiency")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("TargetLoadedMileRatio")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("TargetResponseTime")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetRevenuePerHour")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WaitTimeWeight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("RouteOptimizationSettings");
                });

            modelBuilder.Entity("Medport.Domain.Entities.SystemAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetricValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemAnalytics");
                });

            modelBuilder.Entity("Medport.Domain.Entities.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArrivalTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedAgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Bariatric")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DepartureTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationFacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmsCompletionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GenerateQRCode")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HealthcareCompletionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMultiLocationFacility")
                        .HasColumnType("bit");

                    b.Property<bool>("Isolation")
                        .HasColumnType("bit");

                    b.Property<string>("MobilityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MonitoringRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationRadius")
                        .HasColumnType("int");

                    b.Property<Guid?>("OriginFacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OxygenRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PatientAgeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientAgeYears")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PickupLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PickupTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedAgencies")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransportLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TripNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrgencyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUnitId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationFacilityId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("IsMultiLocationFacility");

                    b.HasIndex("OriginFacilityId");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("RequestTimestamp");

                    b.HasIndex("Status");

                    b.HasIndex("TripNumber")
                        .IsUnique()
                        .HasFilter("[TripNumber] IS NOT NULL");

                    b.ToTable("TransportRequest");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ActualTripTimeMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedAgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BackhaulOpportunity")
                        .HasColumnType("bit");

                    b.Property<int?>("CompletionTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerSatisfaction")
                        .HasColumnType("int");

                    b.Property<double?>("DeadheadMiles")
                        .HasColumnType("float");

                    b.Property<double?>("DestinationLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("DestinationLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("float");

                    b.Property<decimal?>("Efficiency")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("EmsArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmsDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedTripTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenerateQRCode")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InsurancePayRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LoadedMiles")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaxResponses")
                        .HasColumnType("int");

                    b.Property<string>("MobilityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MonitoringRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationRadius")
                        .HasColumnType("int");

                    b.Property<double?>("OriginLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("OriginLongitude")
                        .HasColumnType("float");

                    b.Property<bool>("OxygenRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PatientAgeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientAgeYears")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PerMileRate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("PerformanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("PickupLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PickupTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal?>("RevenuePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedAgencies")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransferAcceptedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TransferRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransportLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TripCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("TripNumber")
                        .IsUnique();

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Medport.Domain.Entities.TripCostBreakdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerMile")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CrewLaborCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DeadheadMileRatio")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("DeadheadMiles")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("InsuranceAdjustment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("LoadedMileRatio")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("LoadedMiles")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MaintenanceCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MileageRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OverheadCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriorityRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RevenuePerMile")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("SpecialRequirementsRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransportLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TripDistance")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TripDurationHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UtilizationRate")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("VehicleCost")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("TripCostBreakdown");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrewSize")
                        .HasColumnType("int");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastStatusUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NextMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Status");

                    b.HasIndex("AgencyId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Medport.Domain.Entities.UnitAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageResponseTime")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Efficiency")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PerformanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.Property<int>("TotalTripsCompleted")
                        .HasColumnType("int");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnitId")
                        .IsUnique();

                    b.ToTable("UnitAnalytics");
                });

            modelBuilder.Entity("Medport.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LastActivity");

                    b.HasIndex("LastLogin");

                    b.HasIndex("OrganizationId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Medport.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PreferenceType")
                        .IsUnique();

                    b.ToTable("UserPreference");
                });

            modelBuilder.Entity("Medport.Domain.Entities.AgencyResponse", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Unit", "AssignedUnit")
                        .WithMany("AgencyResponses")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.TransportRequest", "TransportRequest")
                        .WithMany("AgencyResponses")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUnit");

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("Medport.Domain.Entities.CategoryDefault", b =>
                {
                    b.HasOne("Medport.Domain.Entities.DropdownOption", "Option")
                        .WithOne("DefaultFor")
                        .HasForeignKey("Medport.Domain.Entities.CategoryDefault", "OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Medport.Domain.Entities.DropdownOption", b =>
                {
                    b.HasOne("Medport.Domain.Entities.DropdownCategory", "DropdownCategory")
                        .WithMany("Options")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DropdownCategory");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Facility", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Organization", "Organization")
                        .WithMany("Facilities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Medport.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("Medport.Domain.Entities.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medport.Domain.Entities.OrganizationPreference", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Organization", "Organization")
                        .WithMany("Preferences")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medport.Domain.Entities.Organization", "TargetOrganization")
                        .WithMany("IncomingPreferences")
                        .HasForeignKey("TargetOrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Organization");

                    b.Navigation("TargetOrganization");
                });

            modelBuilder.Entity("Medport.Domain.Entities.PickupLocation", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Facility", "Facility")
                        .WithMany("PickupLocations")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Medport.Domain.Entities.TransportRequest", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Unit", "AssignedUnit")
                        .WithMany("AssignedTrips")
                        .HasForeignKey("AssignedUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTrips")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.Facility", "DestinationFacility")
                        .WithMany("DestinationTrips")
                        .HasForeignKey("DestinationFacilityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.Facility", "FromFacility")
                        .WithMany("FromTrips")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.Facility", "OriginFacility")
                        .WithMany("OriginTrips")
                        .HasForeignKey("OriginFacilityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Medport.Domain.Entities.PickupLocation", "PickupLocation")
                        .WithMany("Trips")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedUnit");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DestinationFacility");

                    b.Navigation("FromFacility");

                    b.Navigation("OriginFacility");

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Medport.Domain.Entities.PickupLocation", "PickupLocation")
                        .WithMany("LegacyTrips")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Organization", "Agency")
                        .WithMany("Units")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Medport.Domain.Entities.UnitAnalytics", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Unit", "Unit")
                        .WithOne("Analytics")
                        .HasForeignKey("Medport.Domain.Entities.UnitAnalytics", "UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Medport.Domain.Entities.User", b =>
                {
                    b.HasOne("Medport.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Medport.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("Medport.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medport.Domain.Entities.DropdownCategory", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Medport.Domain.Entities.DropdownOption", b =>
                {
                    b.Navigation("DefaultFor");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Facility", b =>
                {
                    b.Navigation("DestinationTrips");

                    b.Navigation("FromTrips");

                    b.Navigation("OriginTrips");

                    b.Navigation("PickupLocations");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("IncomingPreferences");

                    b.Navigation("Preferences");

                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Medport.Domain.Entities.PickupLocation", b =>
                {
                    b.Navigation("LegacyTrips");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Medport.Domain.Entities.TransportRequest", b =>
                {
                    b.Navigation("AgencyResponses");
                });

            modelBuilder.Entity("Medport.Domain.Entities.Unit", b =>
                {
                    b.Navigation("AgencyResponses");

                    b.Navigation("Analytics");

                    b.Navigation("AssignedTrips");
                });

            modelBuilder.Entity("Medport.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedTrips");

                    b.Navigation("NotificationLogs");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
